
data:
  input_path: "data/input/retire.csv"
  model_path: "data/models/model_v1.pkl"
  batch_output: data/output/predictions.csv 

training:
  target: score 
  test_size: 0.2
  random_state: 42
  n_estimators: 100

monitoring:
  drift_threshold: 0.15
  retrain_frequency: "monthly"

monitoring:
  drift_report: "data/output/drift_report.html"
  performance_log: data/output/performance_log.csv


mlflow:
  tracking_uri: "file:./mlruns"
  experiment_name: "retirement_model"
