name: CI

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
      - init-structure
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run linter (flake8)
        run: |
          pip install flake8
          flake8 .

      - name: Run tests (placeholder)
        run: echo "No tests yet"

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image to GHCR
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/shanurwan/will-i-be-okay-at-60:latest
            ghcr.io/shanurwan/will-i-be-okay-at-60:${{ github.sha }}

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for GCP Artifact Registry
        run: |
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev

      - name: Build and push to GCP Artifact Registry
        run: |
          IMAGE_URI=asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO }}/will-i-be-okay-at-60:latest
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Deploy to Cloud Run
        run: |
          IMAGE_URI=asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO }}/will-i-be-okay-at-60:latest
          gcloud run deploy retirement-app \
            --image=$IMAGE_URI \
            --region=${{ secrets.GCP_REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --set-env-vars FEEDBACK_WEBHOOK=https://script.google.com/macros/s/AKfycbym3BvAAMXTTpvNEKPnbCSEZNW9pcFryfLTliP3k2_jq_RqmNwuA_t4rxPfvNBjGZP9/exec

