name: CI

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
      - init-structure
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run linter (flake8)
        run: |
          pip install flake8
          flake8 .

      - name: Run tests (placeholder)
        run: echo "No tests yet"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/shanurwan/will-i-be-okay-at-60:latest
            ghcr.io/shanurwan/will-i-be-okay-at-60:${{ github.sha }}

